input_features:

- name: content_rating
  type: category
- name: genres
  type: set
  preprocessing:
    tokenizer: comma
- name: runtime
  type: number
- name: top_critic
  type: binary
- name: review_content
  type: text
output_features:
- name: recommended
  type: binary
hyperopt:
  goal: maximize
  output_feature: recommended
  metric: accuracy
  split: validation
  parameters:
    training.learning_rate:
      space: loguniform
      lower: 0.0001
      upper: 0.1
    training.optimizer.type:
      space: choice
      categories: [sgd, adam, adagrad]
  search_alg:
    type: variant_generator
  executor:
    num_samples: 10
