input_features:
- name: content_rating
  type: category
- name: genres
  type: set
- name: runtime
  type: number
- name: top_critic
  type: binary
- name: review_content
  type: text
output_features:
- name: recommended
  type: binary
hyperopt:
  search_alg:
    type: hyperopt
    random_state_seed: 42
  executor:
    type: ray
    num_samples: 4
    time_budget_s: 3600
    scheduler:
      type: async_hyperband
      time_attr: time_total_s
      max_t: 7200
      grace_period: 72
      reduction_factor: 5
    cpu_resources_per_trial: 5
    gpu_resources_per_trial: 0
    max_concurrent_trials: 4
  parameters:
    trainer.learning_rate:
      space: loguniform
      lower: 2.0e-05
      upper: 0.001
    trainer.batch_size:
      space: choice
      categories:
      - 16
      - 32
      - 64
    combiner.num_fc_layers:
      space: randint
      lower: 1
      upper: 4
    combiner.output_size:
      space: choice
      categories:
      - 16
      - 32
      - 64
    combiner.dropout:
      space: uniform
      lower: 0.0
      upper: 0.1
  output_feature: recommended
  metric: accuracy
  goal: maximize
defaults:
  text:
    encoder:
      type: bert
      trainable: true
  set:
    preprocessing:
      tokenizer: comma
      trainable: true
combiner:
  type: concat
