trainer:
  batch_size: auto
  learning_rate: 1e-05
  epochs: 10
  learning_rate_scheduler:
    warmup_fraction: 0.1
    decay: linear
  optimizer:
    type: adamw
  use_mixed_precision: true
  validation_field: recommended
  validation_metric: roc_auc
hyperopt:
  search_alg:
    type: variant_generator
    random_state_seed: 42
  executor:
    type: ray
    num_samples: 10
    time_budget_s: 7200
    scheduler:
      type: async_hyperband
      time_attr: time_total_s
      max_t: 7200
      grace_period: 72
      reduction_factor: 5
    cpu_resources_per_trial: 5
    gpu_resources_per_trial: 1
  parameters:
    trainer.learning_rate:
      space: loguniform
      lower: 2e-05
      upper: 0.001
    trainer.batch_size:
      space: choice
      categories:
      - 64
      - 128
      - 256
      - 512
      - 1024
    combiner.num_fc_layers:
      space: randint
      lower: 1
      upper: 4
    combiner.output_size:
      space: choice
      categories:
      - 128
      - 256
    combiner.dropout:
      space: uniform
      lower: 0.0
      upper: 0.1
    training.learning_rate:
      space: loguniform
      lower: 0.0001
      upper: 0.1
    training.optimizer.type:
      space: choice
      categories:
      - sgd
      - adam
      - adagrad
    review_content.embedding_size:
      space: choice
      categories:
      - 128
      - 256
  goal: maximize
  output_feature: recommended
  metric: accuracy
  split: validation
input_features:
- name: 'Unnamed: 0'
  column: 'Unnamed: 0'
  type: number
- name: movie_title
  column: movie_title
  type: category
- name: content_rating
  column: content_rating
  type: category
- name: genres
  column: genres
  type: category
- name: runtime
  column: runtime
  type: number
- name: top_critic
  column: top_critic
  type: binary
- name: review_content
  column: review_content
  type: text
  encoder:
    type: bert
output_features:
- name: recommended
  column: recommended
  type: binary
preprocessing:
  split:
    type: stratify
    column: recommended
defaults:
  text:
    encoder:
      type: bert
      trainable: true
combiner:
  type: concat
